### PR TITLE
Adds GPT action cookbook about connecting to Google Ads real-time reporting data

### PR DESCRIPTION
**Pull request by GoooGu**
## Summary

This PR aims to expands the cookbook library on GPT actions by adding a new one about Google Ads. This cookbook explains how to connect to Google Ads reporting data to ChatGPT via Adzviser, a 3rd-party middleware that retrieves and transforms the Google Ads data for the user.

## Motivation

There are many marketers who use ChatGPT on a daily basis today. Some upload their downloaded reporting data files from Google Ads UI to ChatGPT for it to analyze it deeper and brainstorm optimization ideas. This cookbook gives a tutorial on how to connect Google Ads reporting data directly to ChatGPT through GPT actions, so that marketers don't have to download and upload files each time. It will save them time and overheads.  

---

## For new content

When contributing new content, read through our [contribution guidelines](https://github.com/openai/openai-cookbook/blob/main/CONTRIBUTING.md), and mark the following action items as completed:

- [x] I have added a new entry in [registry.yaml](https://github.com/openai/openai-cookbook/blob/main/registry.yaml) (and, optionally, in [authors.yaml](https://github.com/openai/openai-cookbook/blob/main/authors.yaml)) so that my content renders on the cookbook website.
- [x] I have conducted a self-review of my content based on the [contribution guidelines](https://github.com/openai/openai-cookbook/blob/main/CONTRIBUTING.md#rubric):
  - [x] Relevance: This content is related to building with OpenAI technologies and is useful to others.
  - [x] Uniqueness: I have searched for related examples in the OpenAI Cookbook, and verified that my content offers new insights or unique information compared to existing documentation.
  - [x] Spelling and Grammar: I have checked for spelling or grammatical mistakes.
  - [x] Clarity: I have done a final read-through and verified that my submission is well-organized and easy to understand.
  - [x] Correctness: The information I include is correct and all of my code executes successfully.
  - [x] Completeness: I have explained everything fully, including all necessary references and citations.

We will rate each of these areas on a scale from 1 to 4, and will only accept contributions that score 3 or higher on all areas. Refer to our [contribution guidelines](https://github.com/openai/openai-cookbook/blob/main/CONTRIBUTING.md) for more details.

### CODE REVIEW

**Comment by GoooGu** [comment]
@pap-openai, do you mind reviewing this PR so that we could add tutorials about Google Ads connector to our Cookbook? Thanks in advance. This entire cookbook library has been instrumental for us.

**Comment by GoooGu** [comment]
@pap-openai, @aaronwilkowitz-openai, @joecasson-openai, @msingh-openai 

Hey! Sorry for the follow-up, but could you review this PR when you get a chance? I'd love to make this my first contribution to the cookbook! 🙇 Thanks so much!

**Comment by GoooGu** [comment]
@pap-openai, @aaronwilkowitz-openai, @joecasson-openai, @msingh-openai

Gentle ping again. Thanks in advance guys.

**Comment by GoooGu** [comment]
@pap-openai, @aaronwilkowitz-openai, @joecasson-openai, @msingh-openai

Gentle ping. Thanks in advance guys.

**Comment by GoooGu** [comment]
Gentle ping. Trying to see if this PR could get a review before the Thanksgiving holidays.

**Comment by GoooGu** [comment]
Gentle ping again. @pap-openai, @aaronwilkowitz-openai, @joecasson-openai, @msingh-openai

Trying again to see if anyone could take a look at this PR. This PR gives instructions on how marketers could retrieve real-time Google Ads data directly to ChatGPT.

**Comment by GoooGu** [comment]
@pap-openai, @aaronwilkowitz-openai, @joecasson-openai, @msingh-openai

Hope you guys had a great weekend. Gentle ping on this PR again. It would benefit PPC marketers to get their real-time Google Ads data to GPTs.

**Review by ibigio — APPROVED** [review]
Nice, thank you for the contribution!

| Criteria     | Description                                                                                         | Score |
| ------------ | --------------------------------------------------------------------------------------------------- | ----- |
| Relevance    | Is the content related to building with OpenAI technologies? Is it useful to others?                |      3 |
| Uniqueness   | Does the content offer new insights or unique information compared to existing documentation?       |    4   |
| Clarity      | Is the language easy to understand? Are things well-explained? Is the title clear?                  |      4 |
| Correctness  | Are the facts, code snippets, and examples correct and reliable? Does everything execute correctly? |    4   |
| Conciseness  | Is the content concise? Are all details necessary? Can it be made shorter?                          |    3   |
| Completeness | Is the content thorough and detailed? Are there things that weren’t explained fully?                |     4  |
| Grammar      | Are there grammatical or spelling errors present?                                                   |     4  |

**Pull request merged**
