### PR TITLE
Add example notebook with Deep Lake vector database

### PR DESCRIPTION
**Pull request by FayazRahman**
## Summary

Added an example notebook that shows how to implement a QA system with LangChain's [Deep Lake](https://www.deeplake.ai/) integration as a vector store and OpenAI embeddings.

## Changes

List the major and minor changes.

- Major Changes
  - Adds a new vector database example
- Minor Changes
  - ...

## Motivation

Add a new vector database to the collection, hence expanding the cookbook. 

## Self Review Checklist

- [x] Is the writing easily skimmable?
  - Sections have informative titles.
  - Key takeaways are upfront.
  - Short paragraphs and topic sentences are used.
- [x] Is the writing quality high?
  - Sentences are simple and unambiguous.
  - Demonstrative pronouns are avoided or clearly referenced.
  - No left-branching sentences.
- [x] Is the content universally helpful?
  - Terminology is specific and avoids jargon.
  - Provides solutions to common problems.
  - Code examples are general and exportable.
- [x] Is the content consistent?
  - Styling and formatting align with existing documentation.
  - Consistent use of punctuation and case.

**Note:** For additional guidelines on writing good documentation, check out [What Makes Documentation Good](https://cookbook.openai.com/what_makes_documentation_good).

### CODE REVIEW

**Comment by mikayelh** [comment]
hi there @logankilpatrick , bumping this up in case it's possible to merge to add Deep Lake to the list of vector databases, we need more open source ones out there:)

**Comment by mikayelh** [comment]
hi @ted-at-openai, just noticed you review a [similar pr ](https://github.com/openai/openai-cookbook/pull/489). Would really appreciate you taking a look at this, too, as it has been up there for a while now.

**Review by simonpfish — CHANGES_REQUESTED** [review]
Hi @FayazRahman and @mikayelh. Apologies for the delay in reviewing this PR, and thank you for your contribution. 

I just ran through the notebook and noticed a couple of broken links. It also looks like you're using a deprecated langchain api. 

CleanShot 2023-09-27 at 15 40 58@2x

Would it also be possible for you guys to fill out our new [pull request template]( https://github.com/openai/openai-cookbook/blob/main/.github/pull_request_template.md)? Let us know if you have any feedback on this template!

**Comment by FayazRahman** [comment]
@simonpfish I have updated the PR and the description, hope everything looks good now!

**Comment by simonpfish** [comment]
Looks good! Thank you for doing that. One last thing, I'd recommend dealing with this deprecation warning and using the latest version of that function:

CleanShot 2023-09-28 at 17 56 26@2x

And completely optional, but sometimes I find it helpful to hide the outputs of the installation cell to make the notebooks easier to read.

CleanShot 2023-09-28 at 17 55 56@2x

**Comment by FayazRahman** [comment]
@simonpfish Fixed!

**Review by simonpfish — APPROVED** [review]

**Comment by simonpfish** [comment]
Thanks for the contribution!

**Pull request merged**
