### PR TITLE
Update stream chat completions API cookbook

### PR DESCRIPTION
**Pull request by brianz-openai**
## Summary

image

## Motivation

Why are these changes necessary? How do they improve the cookbook?

---

## For new content

When contributing new content, read through our [contribution guidelines](https://github.com/openai/openai-cookbook/blob/main/CONTRIBUTING.md), and mark the following action items as completed:

- [ ] I have added a new entry in [registry.yaml](https://github.com/openai/openai-cookbook/blob/main/registry.yaml) (and, optionally, in [authors.yaml](https://github.com/openai/openai-cookbook/blob/main/authors.yaml)) so that my content renders on the cookbook website.
- [x] I have conducted a self-review of my content based on the [contribution guidelines](https://github.com/openai/openai-cookbook/blob/main/CONTRIBUTING.md#rubric):
  - [x] Relevance: This content is related to building with OpenAI technologies and is useful to others.
  - [x] Uniqueness: I have searched for related examples in the OpenAI Cookbook, and verified that my content offers new insights or unique information compared to existing documentation.
  - [x] Spelling and Grammar: I have checked for spelling or grammatical mistakes.
  - [x] Clarity: I have done a final read-through and verified that my submission is well-organized and easy to understand.
  - [x] Correctness: The information I include is correct and all of my code executes successfully.
  - [x] Completeness: I have explained everything fully, including all necessary references and citations.

We will rate each of these areas on a scale from 1 to 4, and will only accept contributions that score 3 or higher on all areas. Refer to our [contribution guidelines](https://github.com/openai/openai-cookbook/blob/main/CONTRIBUTING.md) for more details.

### CODE REVIEW

**Review by owencm — APPROVED** [review]
lgtm

**Comment by owencm** [comment]
Actually one quick thought, can we link to the relevant part of the API reference (the usage key in the chunk section and the stream_option section of the request section?)

The current plan is for the tweet to link to this section of this cookbook, so this will get quite a lot of traffic and it'd be nice if it linked through to the other resources nicely.

**Comment by owencm** [comment]
Also let's mention in this cookbook that `choices` will be `[]` in this case, since I think this will require a code change for a lot of people

**Comment by brianz-openai** [comment]
updated

**Pull request merged**
