### PR TITLE
fix embedding model change and quick code edits

### PR DESCRIPTION
**Pull request by ankur-oai**
## Summary

This [PR](https://github.com/openai/openai-cookbook/commit/f1e13cfcc7e0f2a9015c562eede167b76b1d60fc#diff-a374fc63cb5e9743bb87abf28818712c9eebae0de81d43343008ca6775c53c94) bulk-updated older model names and changed this notebook to use `text-embedding-3-small` but broke it in the process; this notebook relies on comparisons b/w a query string embedding against data from a [CSV](https://cdn.openai.com/API/examples/data/vector_database_wikipedia_articles_embedded.zip) in our CDN that contains vectors generated with `ada-002`.

Also:
- removed some unused variables
- removed an empty code block at the end of the notebook

## Motivation

Why are these changes necessary? How do they improve the cookbook?

Cookbook was not working as expected (bad embedding query results).

---

## For new content

When contributing new content, read through our [contribution guidelines](https://github.com/openai/openai-cookbook/blob/main/CONTRIBUTING.md), and mark the following action items as completed:

- [ ] I have added a new entry in [registry.yaml](https://github.com/openai/openai-cookbook/blob/main/registry.yaml) (and, optionally, in [authors.yaml](https://github.com/openai/openai-cookbook/blob/main/authors.yaml)) so that my content renders on the cookbook website.
- [ ] I have conducted a self-review of my content based on the [contribution guidelines](https://github.com/openai/openai-cookbook/blob/main/CONTRIBUTING.md#rubric):
  - [ ] Relevance: This content is related to building with OpenAI technologies and is useful to others.
  - [ ] Uniqueness: I have searched for related examples in the OpenAI Cookbook, and verified that my content offers new insights or unique information compared to existing documentation.
  - [ ] Spelling and Grammar: I have checked for spelling or grammatical mistakes.
  - [ ] Clarity: I have done a final read-through and verified that my submission is well-organized and easy to understand.
  - [ ] Correctness: The information I include is correct and all of my code executes successfully.
  - [ ] Completeness: I have explained everything fully, including all necessary references and citations.

We will rate each of these areas on a scale from 1 to 4, and will only accept contributions that score 3 or higher on all areas. Refer to our [contribution guidelines](https://github.com/openai/openai-cookbook/blob/main/CONTRIBUTING.md) for more details.

### CODE REVIEW

**Review by shyamal-anadkat — APPROVED** [review]

**Comment by sarbazvatanatan** [comment]
Very good

**Comment by sarbazvatanatan** [comment]
Hard

**Comment by sarbazvatanatan** [comment]
1. Hdcj

**Comment by sarbazvatanatan** [comment]
Hoo

**Comment by sarbazvatanatan** [comment]
****

**Pull request closed without merging**
