### PR TITLE
Add LMQL to README

### PR DESCRIPTION
**Pull request by lbeurerkellner**
It would be awesome if [LMQL](https://lmql.ai) was included in the list of prompting libraries and tools.

LMQL is an open source programming language for large language models. It supports typed prompting with control flow, constraints, and tools. 

We started working on LMQL in June 2022 and also wrote a paper about it

*Prompting Is Programming: A Query Language for Large Language Models*, https://arxiv.org/abs/2212.06094, which was accepted to PLDI'23. 

I respect the choice of papers that you highlight in the README, so I limited this PR to the inclusion of our project page for now.

### CODE REVIEW

**Comment by ted-at-openai** [comment]
Looks cool. Do you have much traction yet? How do you think you compare to other libraries out there?

**Comment by ted-at-openai** [comment]
(I tried to join your Discord, but got some kind of error.)

**Comment by lbeurerkellner** [comment]
What kind of error did you get on Discord? Just in case, here is another [Invite Link](https://discord.gg/5djae9gJVB) :).

Although, initially published in Nov'22 on arXiv, LMQL publicly launched as an open source project in the beginning of April and ever since has experienced consistent community growth (1.5k stars, 400+ Discord users and growing daily). We are also actively working with several other open source community, like the one surrounding AutoGPT and MultiGPT, who integrate and/or want to integrate LMQL in their project.

In spirit, LMQL is closest to `guidance`, although developed concurrently. In contrast to simple templating, however, our focus is more on building a PL that natively integrates LLMs, including types, algorithmic use, functions and tool use, while also being deeply integrated with Python (e.g. calling functions during decoding, variable captures, query programs as class methods, etc.). A more thorough comparison with `guidance` can be found here: https://docs.lmql.ai/en/latest/python/comparison.html, including a selection of advanced use cases, not possible with current LLM tooling, even guidance.

Beyond this, LMQL differentiates with respect to existing tool by not operating on a simple text API, but rather by being deeply integrated into the token-by-token decoding process of LLMs (even with OpenAI models). This allows us to eagerly enforce and validate constraints (via logit masking), whereas other text-based libraries have to resort to re-prompting or backtracking. This also makes LMQL much more efficient with respect to token use, especially when used with models with full logit access. We also implement an advanced caching layer, that allows us to decode multi-part templates with fewer requests, by heavily relying on [speculative LLM execution](https://lmql.ai/blog/release-0.0.6.html).

With respect to constraints, we also support advanced character-level constraining and implement a formal, extendible constraint language (see paper for semantics). This will soon also include full parser and Regex support, facilitating control text generation. We also already have type constraints (schema-safe decoding) in our `preview` channel available via https://next.lmql.ai. 

I hope this helps highlight our work on LMQL a bit, with respect to existing tooling.

**Comment by ted-at-openai** [comment]
Very cool! Added.

**Pull request merged**
