### PR TITLE
Add getting started with PolarDB vector database and OpenAI example.

### PR DESCRIPTION
**Pull request by liuchengshan-lcs**

### CODE REVIEW

**Comment by liuchengshan-lcs** [comment]
Looking forward to the merge of PolarDG's submission :)

**Comment by ted-at-openai** [comment]
Thanks for the contribution, and for your patience. I'll review this week. Any feedback you're looking for, in particular?

**Comment by liuchengshan-lcs** [comment]
Thank you for your review. If it can be merged, it is best. Polardb has a large number of global users, and has advantages in vector computing such as EPQ parallelism and shared storage architecture, resulting in significant speed and efficiency in vector computing. If there are any issues that cannot be accepted, I hope you can provide feedback and I will be responsible for repairing them. We are also developing more applications based on OpenAI and Polardb, and we hope to make more and more contributions to you in the future:)

**Review by ted-at-openai — CHANGES_REQUESTED** [review]
Looks great. Thanks for the contribution and for your patience for my review.

I have just one change to request. Do you mind taking out the cell that says:
```
"os.environ['OPENAI_API_KEY'] = 'sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'"
```

In general I don't want to encourage people to write their API keys in code. I think you have a later cell that reads from environment variables that should work. Our Python library also automatically reads from environment variables.

You can optionally link to our API key safety guide if you think it will help people not get stuck on how to set environment variables: https://help.openai.com/en/articles/5112595-best-practices-for-api-key-safety

**Comment by liuchengshan-lcs** [comment]
Thank you for the review. I have followed your suggestions and removed the API keys, providing a link to the instructional manual. In our future code submissions, my team and I will pay even more attention to this aspect. Thank you for your efforts in reviewing once again.

**Comment by liuchengshan-lcs** [comment]
Could you please review whether it is possible to merge the code? Thank you :)

**Review by ted-at-openai — APPROVED** [review]
Approved. Merging now.

**Pull request merged**
