### PR TITLE
add parea

### PR DESCRIPTION
**Pull request by joschkabraun**
Adding Parea (YC S23) to relevant resources.

### CODE REVIEW

**Comment by joschkabraun** [comment]
cc: @simonpfish

**Comment by simonpfish** [comment]
Hey! Would love to learn a little bit more about Parea. Looks like a promising app. 

Can you tell me a bit more about what you guys do? How does this compare to other evaluation and LLM observability products out there?

**Comment by joschkabraun** [comment]
We simplify the iterative development cycle (experimentation, testing & monitoring) implementing LLMs. This means users can:

- iterate on prompts in a grid-style playground
- iterate on chains & agents in a code editor & get visibility into intermediate responses across many inputs at the same time
- monitor their production app via SDK and use those logs to define test cases
- use custom evaluation metrics to evaluate LLM responses during experimentation & from production logs
- benchmark prompts, chains & agents on multiple test cases

**Review by simonpfish — APPROVED** [review]

**Comment by simonpfish** [comment]
Very cool! Looks useful

**Pull request merged**
