### PR TITLE
fix: some typo and add execution command sample

### PR DESCRIPTION
**Pull request by liuliuOD**
1. getting-started-with-weaviate-and-openai.ipynb
2. hybrid-search-with-weaviate-and-openai.ipynb
3. question-answering-with-weaviate-and-openai.ipynb

### CODE REVIEW

**Review by arifhossain512 — APPROVED** [review]

**Comment by liuliuOD** [comment]
@ted-at-openai @arifhossain512 Hi there. May I help?

**Comment by sebawita** [comment]
hi @liuliuOD and @ted-at-openai, this is great!
Thank you for doing this. 🙏

Feel free to merge 👍

**Comment by liuliuOD** [comment]
@sebawita @ted-at-openai @arifhossain512 Hola. I'm worried that this PR might become outdate due to inactivity. Maybe we could merge it, right?

**Comment by sebawita** [comment]
@liuliuOD agreed. I am happy for someone to merge it, but I don't have the required permissions ;)

**Comment by ted-at-openai** [comment]
Will merge now. Just got back from a two-week vacation. :)

**Pull request merged**
