### PR TITLE
Update GPT_finetuning_with_wandb.ipynb Example

### PR DESCRIPTION
**Pull request by ash0ts**
## Summary

Update the deprecated wandb - OAI fine-tuning workflow to match the latest version.

## Motivation

This update prevents broken improper workflows by updating them to the most appropriate form
---

## For new content

When contributing new content, read through our [contribution guidelines](https://github.com/openai/openai-cookbook/blob/main/CONTRIBUTING.md), and mark the following action items as completed:

- [ ] I have added a new entry in [registry.yaml](https://github.com/openai/openai-cookbook/blob/main/registry.yaml) (and, optionally, in [authors.yaml](https://github.com/openai/openai-cookbook/blob/main/authors.yaml)) so that my content renders on the cookbook website.
- [ ] I have conducted a self-review of my content based on the [contribution guidelines](https://github.com/openai/openai-cookbook/blob/main/CONTRIBUTING.md#rubric):
  - [ ] Relevance: This content is related to building with OpenAI technologies and is useful to others.
  - [ ] Uniqueness: I have searched for related examples in the OpenAI Cookbook, and verified that my content offers new insights or unique information compared to existing documentation.
  - [ ] Spelling and Grammar: I have checked for spelling or grammatical mistakes.
  - [ ] Clarity: I have done a final read-through and verified that my submission is well-organized and easy to understand.
  - [ ] Correctness: The information I include is correct and all of my code executes successfully.
  - [ ] Completeness: I have explained everything fully, including all necessary references and citations.

We will rate each of these areas on a scale from 1 to 4, and will only accept contributions that score 3 or higher on all areas. Refer to our [contribution guidelines](https://github.com/openai/openai-cookbook/blob/main/CONTRIBUTING.md) for more details.

### CODE REVIEW

**Comment by logankilpatrick** [comment]
Hey @ash0ts can you update this to remove the parts that required that PR you all merged (there is a comment that say to remove it once it lands which it did).

**Review by logankilpatrick — APPROVED** [review]
Approved pending the requested change!

**Comment by ash0ts** [comment]
Fixed @logankilpatrick! Hope your holiday is going well

**Comment by ash0ts** [comment]
@logankilpatrick Hope you had a lovely holiday time! Would love a merge :)

**Comment by ash0ts** [comment]
Sorry for the ping again @logankilpatrick, would love a quick merge :)

**Pull request closed without merging**
