### PR TITLE
Update Weaviate cookbooks

### PR DESCRIPTION
**Pull request by sebawita**

### CODE REVIEW

**Comment by ted-at-openai** [comment]
Thanks for the contribution. Do you feel like this PR is in good shape? Would any particular review or feedback be useful? Will try to run things later this week, before merging, but just wanted to check in before I do.

**Comment by bobvanluijt** [comment]
Hi @ted-at-openai — I've run them as well to test. Feel free to let us know if we've missed something in your opinion

**Comment by sebawita** [comment]
hi @ted-at-openai this should be good to be merged ;)

**Review by colin-openai — CHANGES_REQUESTED** [review]
Can you please replace references to "dataset" with "article_df"?

**Comment by sebawita** [comment]
> Can you please replace references to "dataset" with "article_df"?
I've updated as per your request :)

**Review by colin-openai — APPROVED** [review]
Looks good, changes made

**Pull request merged**
