### PR TITLE
Update FT'ing for function calling notebook to match new python SDK

### PR DESCRIPTION
**Pull request by jhills20**

### CODE REVIEW

**Review by simonpfish — APPROVED** [review]

**Comment by robechun** [comment]
@jhills20 do you have any insight on how to fine-tune 1106 with the new `tools` API format?

**Comment by jhills20** [comment]
hey @robechun I'm making an update with the new spec that uses `tools`, hopefully it will be merged soon!

**Comment by robechun** [comment]
@jhills20 is there a PR I can follow along?

**Comment by jhills20** [comment]
yep, here: https://github.com/openai/openai-cookbook/pull/893

**Pull request merged**
