### PR TITLE
Add W&B embedding projector example

### PR DESCRIPTION
**Pull request by scottire**
Hi,

I've added an example showing how to use the Weights & Biases embedding projector with OpenAI embeddings. Let me know if there's anything I can change to help it get merged. 

Here's an example that was created by it: [http://wandb.me/openai_embeddings](http://wandb.me/openai_embeddings)
You can dynamically change what dimensionality reduction algorithm is used, along with choosing which of your logged data is shown with color & hover.

### CODE REVIEW

**Comment by ted-at-openai** [comment]
Looks great and happy to accept the contribution.

Before merging, I think it might be helpful to add an introductory blurb at the top explaining what W&B is, and why someone might want to use it (or not use it). Some people browsing the Cookbook may never have heard of W&B, so this is a good chance to explain what it is. Mind adding?

**Comment by scottire** [comment]
Of course, that's a good suggestion. I'll follow up with that soon

**Comment by scottire** [comment]
I've added that blurb now. Let me know if there's anything else I can do.

**Comment by ted-at-openai** [comment]
Looks awesome. One tiny request - do you mind rewording 'other top ML teams' to just 'other ML teams'? Would love to keep things as inclusive and humble as possible, especially since people reading this on the OpenAI Cookbook might think OpenAI is writing that about themselves.

After that small change (or equivalent), I'll approve and merge.

**Comment by scottire** [comment]
Great. That should be done now.

**Review by Safar25tory — APPROVED** [review]

**Review by ted-at-openai — APPROVED** [review]

**Comment by ted-at-openai** [comment]
Merged. Thank you again!

**Pull request merged**
