### PR TITLE
Add liteLLM Example - Call Azure, Anthropic, Llama2, Cohere, 50+ LLM APIs using chatGPT input/output

### PR DESCRIPTION
**Pull request by ishaan-jaff**
This PR adds an example notebook of using liteLLM: https://github.com/BerriAI/litellm/

liteLLM is a package to simplify calling OpenAI, Azure, Cohere, Anthropic, Huggingface API Endpoints
**TLDR: Call all LLM APIs using chatGPT input/output formats**

Here's a sample of how it's used:

```
from litellm import completion

## set ENV variables
# ENV variables can be set in .env file, too. Example in .env.example
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["COHERE_API_KEY"] = "cohere key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# llama2 call
model_name = "replicate/llama-2-70b-chat:2c1608e18606fad2812020dc541930f2d0495ce32eee50074220b87300bc16e1"
response = completion(model_name, messages)

# cohere call
response = completion("command-nightly", messages)

# anthropic call
response = completion(model="claude-instant-1", messages=messages)
```

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
@ted-at-openai can you please take a look at this when you get the chance 😊

We built this based on feedback we got from users using reliableGPT

**Comment by simonpfish** [comment]
i don't think this example adds much value, it's very minimal and already covered by the framework's readme. perhaps once the framework gains more traction we could simply link to it's github repo from our list of recommended frameworks

**Comment by krrishdholakia** [comment]
Hi @simonpfish - we're at 40k users, 1.6k stars, 100+ forks. Is that sufficient for being a recommended framework? https://github.com/BerriAI/litellm

**Comment by simonpfish** [comment]
Hey! That does look like good traction. Congrats! Feel free to submit a PR to add a link to the framework to https://github.com/openai/openai-cookbook/blob/main/related_resources.md, which will automatically render at https://cookbook.openai.com/related_resources

**Comment by krrishdholakia** [comment]
@simonpfish feedback ackowledged + PR Made. 
https://github.com/openai/openai-cookbook/pull/757/files#diff-da981eed3c49284d8b6b00d16867b633f1bae007274e5e540b42859c16eca479

"Easily call Anthropic/Huggingface/etc. using the OpenAI format"

**Pull request closed without merging**
