### PR TITLE
Fix bug #884 - Port How_to_finetune_chat_models to API V1

### PR DESCRIPTION
**Pull request by gaborcselle**
## Summary

Fix bug #884 - Migrate `How_to_finetune_chat_models.ipynb` to API V1

## Motivation

The notebook `How_to_finetune_chat_models.ipynb` was no longer working with the API V1 described in the [v1.0.0 migration guide](https://github.com/openai/openai-python/discussions/742)

## Testing info
I tested this manually with Python 3.11.3 and OpenAI Python SDK V1.3.5

### CODE REVIEW

**Comment by gaborcselle** [comment]
@ibigio happy to rerun the code cells as per your comment on the similar PR https://github.com/openai/openai-cookbook/pull/883 - let me know if you'd like that, or prefer a more minimal PR

**Comment by simonpfish** [comment]
Thank you @gaborcselle ! 

Yes - rerunning the cells would be great.

**Comment by gaborcselle** [comment]
Thanks @simonpfish, working on this now!

**Comment by gaborcselle** [comment]
@simonpfish PTAL

**Comment by gaborcselle** [comment]
@simonpfish PTAL

**Comment by gaborcselle** [comment]
Addendum: This PR also fixes #889

**Comment by gaborcselle** [comment]
@simonpfish Friendly ping, would be great to have this fix in!

**Comment by gaborcselle** [comment]
@simonpfish Sorry to bother you, just another friendly ping on this. I think this would be a useful PR that solves both #884 and #889. I just merged the latest changes. Thanks for reviewing it!

**Review by simonpfish — APPROVED** [review]
Sorry for the delays here, thank you for updating this!

**Pull request merged**
