### PR TITLE
Updated plotly version

### PR DESCRIPTION
**Pull request by khaled-wsa**
version 5.13 worked fine.

### CODE REVIEW

**Comment by logankilpatrick** [comment]
Hey! But 5.12 did not work?

**Comment by khaled-wsa** [comment]
I installed the requirements and everything was installed except plotly. I got the following error when I tried to run the python script: 

`ModuleNotFoundError: No module named 'plotly'`. Even though plotly==5.12.0 was listed in the requirements, doing `pip install plotly` installed the version 5.13 automatically, and it works perfectly fine. I'm not sure why plotly==5.12.0 wasn't detected during the pip install, maybe because of the 0 at the end of 5.12.0?? I don't know but installing 5.13 worked fine for me. That's why I made the pull request to update it.

**Comment by logankilpatrick** [comment]
Specifying the ".0" at the end seems like a common workflow: https://plotly.com/python/getting-started/

**Comment by vrunm** [comment]
@khaled-wsa plotly == 5.12 works.

**Pull request closed without merging**
