### PR TITLE
[Azure] add example snippet on how to refresh AAD tokens

### PR DESCRIPTION
**Pull request by kristapratico**

### CODE REVIEW

**Comment by ted-at-openai** [comment]
Thanks!

**Comment by ted-at-openai** [comment]
Looks like this has conflicts with a recent merge - mind updating?

**Comment by kristapratico** [comment]
@ted-at-openai thanks for the quick review! I updated the branch.

**Comment by ted-at-openai** [comment]
Thanks! I'll assume everything is good. Merging now.

**Pull request merged**
