### PR TITLE
Added notebook example for visualizing embeddings in Kangas

### PR DESCRIPTION
**Pull request by dsblank**
Plots UMAP projection space, one per row, in open source Kangas DataGrid.

For more information about Kangas, see: https://github.com/comet-ml/kangas

### CODE REVIEW

**Comment by dsblank** [comment]
@ted-at-openai Let us know if there are any refinements you would like. Thanks!

**Review by NazariiuS — COMMENTED** [review]
stechyshynnazarii@gmail.com

**Review by ted-at-openai — CHANGES_REQUESTED** [review]
Looks great. Thanks for the contribution!

I have just one change to request - do you mind putting the notebook in the recently created `examples/third_party_examples/` directory?

We're trying to balance accepting excellent third-party contributions without blurring the lines between what's official OpenAI documentation vs content from other developers.

**Comment by dsblank** [comment]
Sure will do!

**Comment by dsblank** [comment]
Done!

**Review by ted-at-openai — APPROVED** [review]
Thanks for your patience. Just got back from vacation. Merging now.

**Comment by dsblank** [comment]
Thank you! Welcome back :)

**Pull request merged**
