### PR TITLE
Add Qdrant notebooks

### PR DESCRIPTION
**Pull request by kacperlukawski**
This PR adds two additional notebooks on how to use Qdrant as a vector database with OpenAI embeddings. The changes include the following:
- "Getting started with Qdrant and OpenAI" notebook with end-to-end processing of search using the embeddings
- "QA with Langchain Qdrant and OpenAI" notebook with an example of using Qdrant and OpenAI in a Langchain application to create a Question-Answering system. The library is becoming popular, and due to many questions around that, I want to show that case.

@colin-openai, Could you please review the notebooks?

### CODE REVIEW

**Comment by kacperlukawski** [comment]
@logankilpatrick @ted-at-openai @colin-openai Hi guys, could somebody have a look at the notebooks?

**Review by colin-openai — CHANGES_REQUESTED** [review]
Can you please fix the typos we discussed and add an example of using a custom prompt to retrieve docs from the Q&A example.

Happy to approve after this is done.

**Comment by kacperlukawski** [comment]
@colin-openai The changes have been made. I'd appreciate another review ;)

**Review by colin-openai — APPROVED** [review]
Looks good with changes, approved

**Review by colin-openai — COMMENTED** [review]
changes implemented, looks good

**Pull request merged**
