### PR TITLE
fix iteration error

### PR DESCRIPTION
**Pull request by justanotherlad**
array iteration error: sentences up till max_len of token exceeds should be returned

Here's a screenshot of before and after the change (vertically in terminal) in the code. Clearly, the below should be returned: (The numbers vertically represent _*current tokens*_ and _*total_tokens*_ number for each iteration.

Screenshot from 2023-03-07 21-16-59

### CODE REVIEW

**Comment by ted-at-openai** [comment]
Great catch and thanks for the super helpful documentation.

Would it be easier just to write `sentences[:i]` instead of `sentences[:i+1][:-1]`? Seems odd that the list is being sliced twice in the first place.

But happy to merge as is if you don't feel like doing any extra work. Your work so far is already appreciated.

**Comment by justanotherlad** [comment]
Also, please see my comment on [ Document Library Pre-Processing #79 ](https://github.com/openai/openai-cookbook/issues/79#issuecomment-1467670185). I think there might be a bug there.

**Comment by justanotherlad** [comment]
@ted-at-openai Do you want to close/merge this PR?

**Comment by ted-at-openai** [comment]
Thanks! Merged.

**Pull request merged**
