### PR TITLE
add new example notebook for knowledge base chat with automatic data filtering

### PR DESCRIPTION
**Pull request by AlexZhangji**
## Summary
This notebook illustrates a workflow for knowledge-based chat interactions that utilize automatic data filtering through function calls. 

## Motivation
It's common to target specific data subsets; for example, in an Earnings Call Transcript dataset (with multiple companies and many calls across whole year), one might only interested in Nvidia's Q3 performance. However, a simple semantic search, even when enriched with date augmentation, often isn't comprehensive enough. This notebook provides a method for precise question-answering using contextually filtered data. 

For instance, asking question like "whats Microsoft says about Azure in Q3 that year?" triggers call like `{'query': 'Azure in Q3', 'company_names': ['Microsoft Corporation (MSFT)'], 'start_date': '2020-07-01', 'end_date': '2020-09-30'}` to first filter dataset for more relevant ones. Before going into the RAG and chat process. 

Additionally,  feels we can use more examples on function callings.

### CODE REVIEW

**Comment by simonpfish** [comment]
Hi @AlexZhangji! Thank you for your contribution. Since this is a new content addition, it'll take us some time to review it. We'll get to it soon!

**Comment by AlexZhangji** [comment]
> Hi @AlexZhangji! Thank you for your contribution. Since this is a new content addition, it'll take us some time to review it. We'll get to it soon!

Thank you Simon! no problem at all, and happy to answer any questions.

**Comment by simonpfish** [comment]
Hi @AlexZhangji! We just wrote a new set of [contribution guidelines](https://github.com/openai/openai-cookbook/blob/main/CONTRIBUTING.md) for the cookbook, and updated our PR template. I'll review your notebook tomorrow, but in the meantime feel free to look at those resources if you're curious. I'll be referring to them as I review your PR.

**Comment by AlexZhangji** [comment]
> Hi @AlexZhangji! We just wrote a new set of [contribution guidelines](https://github.com/openai/openai-cookbook/blob/main/CONTRIBUTING.md) for the cookbook, and updated our PR template. I'll review your notebook early next week (apologies for the delay), but in the meantime feel free to look at those resources if you're curious. I'll be referring to them as I review your PR.

Thank you!

**Comment by simonpfish** [comment]
Hi @AlexZhangji, thank you for your contribution! While the topic you've chosen seems relevant and promising, this guide needs improvement around its structure and language. I will be closing this PR for now.

| Criteria    | Score | Description                                                                              |
|-------------|-------|------------------------------------------------------------------------------------------|
| Relevance   | 3     | Relevant, but the impact needs to be articulated more clearly.                          |
| Uniqueness  | 3     | Unique with minor overlaps.                                                              |
| Clarity     | 1     | Large sections of code are not explained; language is unclear in many cases; content is hard to read and follow. |
| Correctness | 3     | Code works correctly, minor improvements needed.                                      |
| Grammar     | 1     | Multiple grammatical errors, starting with the title, and numerous typos throughout.     |

Refer to our [contribution guidelines](https://github.com/openai/openai-cookbook/blob/main/CONTRIBUTING.md) for more details on this assessment.

**Comment by AlexZhangji** [comment]
> Hi @AlexZhangji, thank you for your contribution! While the topic you've chosen seems relevant and promising, this guide needs improvement around its structure and language. I will be closing this PR for now.
> 
> Criteria	Score	Description
> Relevance	3	Relevant, but the impact needs to be articulated more clearly.
> Uniqueness	3	Unique with minor overlaps.
> Clarity	1	Large sections of code are not explained; language is unclear in many cases; content is hard to read and follow.
> Correctness	3	Code works correctly, minor improvements needed.
> Grammar	1	Multiple grammatical errors, starting with the title, and numerous typos throughout.
> Refer to our [contribution guidelines](https://github.com/openai/openai-cookbook/blob/main/CONTRIBUTING.md) for more details on this assessment.

Thank you, Simon, for your in-depth feedback.

I understand the current content may not stand alone as its own notebook, but I think automatic data filtering through function calls presents a feature with broad applicability.

Wonder would it add value to integrate this as an additional section within the existing [notebook on function calling with knowledge retrieval](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_call_functions_for_knowledge_retrieval.ipynb)? (I can streamline the more extensive portions of my current notebook to focus only on the essential aspects.) 

I envision an added segment in the existing notebook that expand upon original content. It will not only illustrate interaction with a knowledge base but also delve into the application of an automated filter. 
This would allow for nuanced searches, such as querying the `CLIP model`,  allow to search `CLIP model released this year`, or even specifics like `CLIP papers published after June in the primary category of computer vision` —offering a layer of automated metadata filtering atop natural language queries.

**Comment by simonpfish** [comment]
I’m open to seeing a PR for that! If things are more streamlined and
better explained, it could be helpful as a minimal section on that
notebook.

Simón Fishman
*Applied AI | OpenAI*

**Pull request closed without merging**
