### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Pookam90**
Adding SQL as a Vector Store and linking to the documentation This article provides an overview of using artificial intelligence (AI) options, such as OpenAI and vectors, to build intelligent applications with Azure SQL Database.

## Summary

Briefly describe the changes and the goal of this PR. Make sure the PR title summarizes the changes effectively.

## Motivation

Why are these changes necessary? How do they improve the cookbook?

---

## For new content

When contributing new content, read through our [contribution guidelines](https://github.com/openai/openai-cookbook/blob/main/CONTRIBUTING.md), and mark the following action items as completed:

- [ ] I have added a new entry in [registry.yaml](https://github.com/openai/openai-cookbook/blob/main/registry.yaml) (and, optionally, in [authors.yaml](https://github.com/openai/openai-cookbook/blob/main/authors.yaml)) so that my content renders on the cookbook website.
- [x] I have conducted a self-review of my content based on the [contribution guidelines](https://github.com/openai/openai-cookbook/blob/main/CONTRIBUTING.md#rubric):
  - [x] Relevance: This content is related to building with OpenAI technologies and is useful to others.
  - [x] Uniqueness: I have searched for related examples in the OpenAI Cookbook, and verified that my content offers new insights or unique information compared to existing documentation.
  - [x] Spelling and Grammar: I have checked for spelling or grammatical mistakes.
  - [x] Clarity: I have done a final read-through and verified that my submission is well-organized and easy to understand.
  - [x] Correctness: The information I include is correct and all of my code executes successfully.
  - [x] Completeness: I have explained everything fully, including all necessary references and citations.

We will rate each of these areas on a scale from 1 to 4, and will only accept contributions that score 3 or higher on all areas. Refer to our [contribution guidelines](https://github.com/openai/openai-cookbook/blob/main/CONTRIBUTING.md) for more details.

### CODE REVIEW

**Comment by Pookam90** [comment]
#sign-off

**Comment by Pookam90** [comment]
@ted-at-openai @colin-openai would you be able to review and approve this small change to list SQL as a Vector Database . Link to the documentation & samples have also been added.

**Comment by FardinAhsan146** [comment]
You can include the [pgvector](https://github.com/pgvector/pgvector) extension of Postgres as well given Redis and MongoDB are on the list.

**Comment by Pookam90** [comment]
@FardinAhsan146  this is for Azure SQL DB only. 
pgvector is already listed out with PostgreSQL

**Comment by Pookam90** [comment]
@ted-at-openai @coley-openai could you help with merging this please :)

**Review by shyamal-anadkat — APPROVED** [review]

**Comment by sarbazvatanatan** [comment]
Hi 👋

**Pull request merged**
